### ISSUE TITLE
혹시 이 부분 하나로 통일하는거 어떠신가요?

### ISSUE THREAD

**Issue by Huuuunee** [Gmu-Wiki/Gmu-Wiki-Back#41]
<img width="844" alt="스크린샷 2023-04-27 오후 7 41 56" src="https://user-images.githubusercontent.com/81404026/234839331-d71b8c53-3180-4b4c-8c49-90775922d30c.png">

<img width="1493" alt="스크린샷 2023-04-27 오후 7 41 52" src="https://user-images.githubusercontent.com/81404026/234839407-17f328c8-e30f-409f-94b0-eef47e4cca4b.png">

이 부분 return 부분을 ResponseEntity.ok(body 값) 으로 통일하든 return new ResponseEntity<> 으로 둘중에 하나로 통일하는게 좋을거 같아요!

**Comment by uuuuuuuk** [comment]
반영하겠습니다 감사합니다!
